# Node.jsランタイムを指定
runtime: custom

# 長時間接続やWebSocketをサポートするフレキシブル環境を選択
env: flex

# Socket.IOのために、同じユーザーからの接続は同じインスタンスに送る設定
# これが非常に重要です
network:
  session_affinity: true

# コンピューティングリソースの設定（最初は最小でOK）
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 100

# ヘルスチェックの設定
# Next.jsが起動するまで時間がかかることがあるので、少し長めに設定
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 10
  unhealthy_threshold: 4
  healthy_threshold: 2
